# Generated by Django 4.2.6 on 2023-12-25 08:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник пользователя')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='День рождения пользователя')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Not answered')], default='N/A', max_length=20, verbose_name='Пол пользователя')),
                ('account_image', models.ImageField(default='default.jpg', upload_to='account_images', verbose_name='Аватар пользователя')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='Название статьи')),
                ('anouncement', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Аннотация')),
                ('text', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('category', models.CharField(choices=[('E', 'Экономика'), ('S', 'Наука'), ('IT', 'Ай-Ти'), ('N', 'Природа'), ('H', 'Хобби'), ('Plk', 'Политика'), ('Rus', 'В России'), ('Pc', 'В мире'), ('Hm', 'Наш край')], max_length=20, verbose_name='Категория')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Иллюстрации')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
            options={
                'verbose_name': 'Иллюстрация',
                'verbose_name_plural': 'Иллюстрации',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
