# Generated by Django 4.2.6 on 2023-12-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='default.jpg', upload_to='account_images/', verbose_name='Аватар пользователя'),
        ),
    ]
