# Generated by Django 4.2.6 on 2023-12-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('E', 'Экономика'), ('S', 'Наука'), ('IT', 'Ай-Ти'), ('N', 'Природа'), ('H', 'Хобби'), ('Plk', 'Политика'), ('Rus', 'В России'), ('Pc', 'В мире'), ('Hm', 'Наш край'), ('Km', 'Криминал'), ('Ans', 'Животные')], max_length=20, verbose_name='Категория'),
        ),
    ]
