# Generated by Django 4.2.6 on 2023-12-27 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anouncement',
            field=models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 300 символов')], verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Название статьи'),
        ),
    ]
